server:
  port: 8098
  servlet:
    context-path: /challenge

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: GET, POST, DELETE
  endpoint:
    health:
      enabled: true
    #    flyway:
    #      enabled: true
    info:
      enabled: true
  info:
    git:
      enabled: true
      mode: simple

spring:
  application:
    name: challenge
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  #jpa:
  #  database: default
  #  generate-ddl: false
  #  hibernate:
  #    ddl-auto: validate
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.MySQLDialect
  #      format_sql: true
  #      jdbc:
  #        time_zone: "UTC"
  #      cache:
  #        use_second_level_cache: false
  #  open-in-view: false
  profiles:
    active: dev