logging:
  level:
    org:
      springframework:
        web: DEBUG
      #hibernate:
      #  sql: DEBUG
      #  type.descriptor.sql.BasicBinder: ERROR
    org.tui.org.tui.codechallenge: DEBUG

#spring:
#  datasource:
#    url: ${DB_URL:jdbc:mysql://localhost:3306/challenge?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
#    username: ${DB_USERNAME:user}
#    password: ${DB_PASSWORD:pass123!}
#    hikari:
#      connection-test-query: SELECT 1
#      jdbc-url: ${spring.datasource.url}
#      maximum-pool-size: 17
#      minimum-idle: 10
#      pool-name: datasource-data
#      username: ${spring.datasource.username}
#      password: ${spring.datasource.password}
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration
#  sql:
#    init:
#      mode: always
#  jpa:
#    hibernate:
#    #      ddl-auto: create
#    properties:
#      cache:
#        use_second_level_cache: false
